In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
#binary data
np.save("my_array", arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load("my_array.npy") #先ほど保存したアレイをロードする

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load("my_array.npy") 

In [9]:
arr2 = np.arange(10)

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1

array([0, 1, 2, 3, 4])

In [12]:
#zip形式で保尊
np.savez('ziparrays.npz',x = arr1, y = arr2)

In [14]:
archive_array = np.load("ziparrays.npz")

In [16]:
archive_array

In [17]:
archive_array["x"]

array([0, 1, 2, 3, 4])

In [19]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.array([[1,2,3,4],[4,5,6,7]])

In [21]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [22]:
np.savetxt('my_test_text.txt',arr,delimiter = ',')

In [23]:
arr = np.loadtxt("my_test_text.txt",delimiter = ",")

In [24]:
arr

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])