In [1]:
import numpy as np

In [4]:
arr = np.arange(9).reshape((3,3))

In [6]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr.T # 行と列　入れ替わる

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [10]:
arr.transpose() # 行と列　入れ替わる

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [11]:
arr.transpose((0,1))  #0:行　1：列

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr.transpose((1,0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [14]:
arr.swapaxes(0,1) #　軸入れ替わる時使う

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [15]:
arr.swapaxes(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [16]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.dot(arr.T,arr) # （行*列　掛け算　0*0 + 3*3 + 6*6 = 45）

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [20]:
arr3d = np.arange(12).reshape((3,2,2))

In [22]:
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [24]:
arr3d[0]

array([[0, 1],
       [2, 3]])

In [25]:
arr3d.transpose((0,2,1)) # 

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])

In [26]:
arr = np.arange(11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.sqrt(arr) #平方根

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [30]:
np.exp(arr) #e 2.71828183e+00 の **

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [31]:
A = np.random.randn(10)

In [32]:
A

array([-0.78236458,  0.69650729, -1.09119411, -0.00307843, -0.42087717,
       -2.58103596,  0.56308211,  0.30590181, -1.26879159, -0.17494333])

In [33]:
B = np.random.randn(10)

In [34]:
B

array([ 0.15098696, -2.27772841, -0.9874915 ,  2.07335632, -0.53121023,
        0.16718398,  0.4396692 , -1.43768275, -0.36576457,  1.43985453])

In [35]:
np.add(A,B)

array([-0.63137762, -1.58122112, -2.07868561,  2.07027789, -0.9520874 ,
       -2.41385198,  1.00275131, -1.13178094, -1.63455617,  1.2649112 ])

In [36]:
np.maximum(A,B)

array([ 0.15098696,  0.69650729, -0.9874915 ,  2.07335632, -0.42087717,
        0.16718398,  0.56308211,  0.30590181, -0.36576457,  1.43985453])