In [4]:
import numpy as np

Vector 0 là một vector đặc biệt được dùng rất thường xuyên để khởi tạo. Để tạo một vector 
0 có số phần tử là d, ta dùng hàm numpy.zeros.

In [5]:
np.zeros(3)

array([ 0.,  0.,  0.])

Tương tự như thế, với mảng toàn giá trị 1, ta sẽ dùng hàm numpy.ones:

In [6]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

Ngoài ra, numpy còn cung cấp hai hàm đặc biệt numpy.zeros_like và numpy.ones_like giúp tạo các mảng 0 và mảng 1 có số chiều giống như chiều của biến số.

In [7]:
x = np.array([1,2,3])
np.zeros_like(x)

array([0, 0, 0])

In [8]:
np.ones_like(x)

array([1, 1, 1])

Cấp số cộng
Để tạo mảng các số nguyên từ 0 đến n-1 (n số tổng cộng) ta dùng hàm np.arange(n):

In [9]:
np.arange(3)

array([0, 1, 2])

Để tạo mảng các số nguyên từ m đến n-1, ta cũng dùng hàm này ở dạng np.arange(m, n):

In [10]:
np.arange(3,6)

array([3, 4, 5])

Để tạo một cấp số cộng với phần tử đầu là a, công sai d dương, phần tử cuối là số lớn nhất nhỏ hơn b, ta dùng np.arange(a, b, d).

In [11]:
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

Nếu d là 1 số âm và b < a thì phần tử cuối là phần tử nhỏ nhất của cấp số cộng lớn hơn b:

In [13]:
np.arange(5,1,-0.9)

array([ 5. ,  4.1,  3.2,  2.3,  1.4])

In [15]:
#Bài tập 1: Xây dựng mảng các luỹ thừa của 2 nhỏ hơn 1025, bao gồm cả 1 = 2**0. 
#Gợi ý: Nếu a là một mảng và b là một số thì b**a sẽ trả về một mảng cùng kích thước 
#với a mà phần tử có chỉ số i bằng b**a[i], với ** là toán tử luỹ thừa.

In [21]:
# Ex 1. 
# TODO: create an array comprising of all power of 2 and < 1025, 
# including 1 = 2** 0, store result in x  
x = 2**np.arange(0,11)
x
# -- end TODO ---

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024], dtype=int32)

In [18]:
#Bài tập 2: Xây dựng mảng gồm 10 phần tử, 
#trong đó 9 phần tử đầu bằng 3, phần tử cuối cùng bằng 1.5.

In [25]:
#y = np.array([3,3,3,3,3,3,3,3,3,1.5])
y=np.ones(10)*3
y[-1]=1.5
y

array([ 3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  1.5])