Để truy cập nhiều phần tử của một mảng một chiều một lúc, chúng ta có nhiều cách khác nhau:

Đọc

Ví dụ:

In [2]:
import numpy as np
a = 0.5*np.arange(10)
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [3]:
ids = [1, 3, 4, 8]
a[ids]

array([ 0.5,  1.5,  2. ,  4. ])

Trong ví dụ này, ids là một list trong Python, các phần tử của nó đều là các số nguyên nằm trong khoảng [-10, 9] nên chúng có thể coi là các chỉ số của mảng a được. a[ids] trả về một mảng numpy, là mảng con của a với các phần tử có chỉ số được chỉ ra trong list các chỉ số ids.

ids cũng có thể là một mảng numpy chứa các số nguyên khac là chỉ số hợp lệ của a.

In [4]:
ids = [1, 3, 4, 10]
a[ids]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [5]:
np_ids = np.arange(1,7,2)
np_ids

array([1, 3, 5])

In [6]:
a[np_ids]

array([ 0.5,  1.5,  2.5])

Ngoài ra, cách đánh chỉ số của mảng numpy cũng sử dụng các quy tắc khác giống như cách đánh chỉ số của một list:

In [18]:
print(a)
a[:3] ## return first three elements

[ 0.   1.   1.   1.   2.   1.   3.   3.5  4.   4.5]


array([ 0.,  1.,  1.])

In [14]:
a[-3:] # return last three elements

array([ 3.5,  4. ,  4.5])

In [15]:
a[1:4]

array([ 0.5,  1. ,  1.5])

Ghi

Ta cũng có thể thay đổi giá trị của nhiều phần tử trong mảng. Ví dụ:

In [16]:
a[[1,3,5]] = 1 # <=> a[1] = a[3] = a[5] = 1
a

array([ 0. ,  1. ,  1. ,  1. ,  2. ,  1. ,  3. ,  3.5,  4. ,  4.5])

In [19]:
a[-3:] = np.array([0, -1, -2])# <=> a[-3] = 0, a[-2] = -1, a[-1] = -2

In [20]:
a

array([ 0.,  1.,  1.,  1.,  2.,  1.,  3.,  0., -1., -2.])

In [21]:
a[::2] # return all elements with even indexs

array([ 0.,  1.,  2.,  3., -1.])

In [23]:
a[::-1] # reverse an array

array([-2., -1.,  0.,  3.,  1.,  2.,  1.,  1.,  1.,  0.])

In [31]:
1%2

1

In [62]:
b = 3
if b == 2:
    print(b)
elif b ==3:
    print(b+1)
else:
    print(0)    

4


In [188]:
c = np.arange(0.0, 12)
c

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.])

In [226]:
c = np.arange(0.0, 12)
for i in range(12):
    if i == 0:
        c[i] = 2
    elif i%2 == 0:
        c[i] = c[i-2] - 0.5
    else:
        c[i] = -1
c

array([ 2. , -1. ,  1.5, -1. ,  1. , -1. ,  0.5, -1. ,  0. , -1. , -0.5,
       -1. ])

Bài tập: Cho trước một số tự nhiên n. Tạo một mảng có n phần tử mà các phần tử có chỉ số chẵn (bắt đầu từ 0) là một cấp số cộng bắt đầu từ 2, công sai bằng -0.5; các phần tử có chỉ số lẻ bằng -1.

Ví dụ:

Với n=4, kết quả trả về là mảng [ 2. -1. 1.5 -1. ]. Với n=5, kết quả trả về là mảng [ 2. -1. 1.5 -1. 1. ].

In [248]:
def myfunc(n):
    a = np.arange(0.0, n)
    for i in range(n):
        if i ==0:
            a[i] = 2
        elif i%2==0:
            a[i] = a[i-2] - 0.5
        else:
            a[i] = -1
    print(a)
myfunc(12)

[ 2.  -1.   1.5 -1.   1.  -1.   0.5 -1.   0.  -1.  -0.5 -1. ]


In [249]:
def myfunc(n):
    a = np.arange(0.0, n)
    for i in range(n):
        if i ==0:
            a[i] = 2
        elif i%2==0:
            a[i] = a[i-2] - 0.5
        else:
            a[i] = -1
    return a
print(myfunc(12))

[ 2.  -1.   1.5 -1.   1.  -1.   0.5 -1.   0.  -1.  -0.5 -1. ]
